/*
REALIZAR OS COMANDOS:

1 - REALIZAR A CONTAGEM DOS REGISTROS EXISTENTES NA TABELA PESSOA, EXIBIR SOMENTE O VALOR TOTAL.

2 - REALIZAR A CONTAGEM DOS REGISTROS EXISTENTES NA TABELA PACIENTE E NA TABELA FUNCIONÁRIO, SOMAR OS DOIS RESULTADOS, MOSTRAR A SOMA DAS TABELAS INDIVIDUAIS E A SOMA DAS DUAS TABELAS.

3 - SELECIONAR E EXIBIR O TOTAL DE CONSULTAS CADASTRADAS NA TABELA.

4 - AGENDAR UMA CONSULTA PARA UM DETERMINADO PACIENTE PARA A DATA DE 25 DE MAIO DE 2024 ÀS 09H.

5 - SELECIONAR O AGENDAMENTO DA CONSULTA DO ITEM 4 EXIBINDO O NOME DO PACIENTE, DO MÉDICO, ESPECIALIDADE E OS DADOS DA CONSULTA.

6 - SELECIONAR TODOS OS LOGINS CADASTRADOS EXIBINDO OS CAMPOS: LOGIN, NOME DA PESSOA, CPF, DATA DE NASCIMENTO E EMAIL.

7 - SELECIONAR TODOS OS LOGINS CADASTRADOS EXIBINDO OS CAMPOS: LOGIN, NOME DA PESSOA, CPF, DATA DE NASCIMENTO E EMAIL. ORDENE POR ORDEM DECRESCENTE.

8 - SELECIONAR TODOS OS MÉDICOS EXIBINDO SUAS RESPECTIVAS ESPECIALIDADES.

9 - SELECIONAR AS CONSULTAS RELACIONADAS A UM DETERMINADO MÉDICO EXIBINDO AS ESPECIALIDADES.

10 - CANCELAR UM AGENDAMENTO DE CONSULTA. (SOMENTE COLABORADORES COM PERFIS ADMIN PODEM REALIZAR ESTA AÇÃO)

11 - EXIBIR TODOS OS PRONTUÁRIOS VINCULADOS A UM DETERMINADO PACIENTE, EXIBIR O NOME DO PACIENTE.

12 - SELECIONAR TODOS OS PRONTUÁRIOS VINCULADOS UMA ÚNICA ESPECIALIDADE RELACIONADOS A UM PACIENTE.

*/




